 # /usr/sbin/netplan status
---
- name: Add ip on Ubunty without NM
  hosts: GrpNew
  become: true

  vars:
    ip_a: ['172.28.59.6/20','172.28.59.5/20']
    gw4: ['172.28.48.1']
    dns4: [ 172.28.48.1, 127.0.0.1 ]

  tasks:

    - name: Get ifname from host
      ansible.builtin.set_fact:        
        ifnames: "{{ ansible_facts['interfaces'] | difference([ 'lo' ]) }}"          
        
    # - debug:
    #     #var=ifnames
    #     msg: "{{ ifnames[0] }} -> {{ ifnames | type_debug }}"
     
    - name: Deploy /etc/netplan/new_ip_static.yaml config for ifname
      ansible.builtin.copy: 
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
                {{ ifnames[0] }}:
                  dhcp4: no
                  addresses: {{ ip_a }}
                  nameservers:
                      addresses: {{ dns4 }}
                  routes:
                    - to: default # could be 0.0.0.0/0 optionally
                      via: 172.28.48.1
                      metric: 100
                      on-link: true
                      advertised-mss: 1400
        dest: /etc/netplan/new_ip_static.yaml
        owner: 'root'
        mode: '0600'
      #when: ifnames[0] == 'eth0'
      register: ip_added

    - name: Apply netplan if required
      command: /usr/sbin/netplan apply
      when: ip_added.changed  # or ip_removed.changed
      check_mode: no

    - name: Remove /etc/netplan/new_ip_static.yaml config-file
      ansible.builtin.file:
        state: absent
        path: /etc/netplan/new_ip_static.yaml
      register: ip_removed              
...
# Run: ansible-playbook --ask-vault-pass --extra-vars '@passwd.yml' 2.Add_IP_Netplan_Ubuntu.yml
# Vault password: 

# PLAY [Add ip on Ubunty without NM] *****************************************************************************************************************************

# TASK [Gathering Facts] *****************************************************************************************************************************************
# ok: [localhost]

# TASK [Get ifname from host] ************************************************************************************************************************************
# ok: [localhost]

# TASK [Deploy /etc/netplan/new_ip_static.yaml config for ifname] ************************************************************************************************
# changed: [localhost]

# TASK [Apply netplan if required] *******************************************************************************************************************************
# changed: [localhost]

# TASK [Remove /etc/netplan/new_ip_static.yaml config-file] ******************************************************************************************************
# changed: [localhost]

# PLAY RECAP *****************************************************************************************************************************************************
# localhost                  : ok=5    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
