# ansible-galaxy collection install ansible.posix
---
- name: Change port and others restrictions in config ssh
  hosts: GrpRH
  become: yes

  vars:
    port_ssh: 14582

  tasks:

    - name: Add new ssh-port via firewalld
      ansible.posix.firewalld:
        port: "{{ port_ssh }}/tcp"
        permanent: yes
        state: enabled
      notify:
        - reload firewalld
      register: add_ssh_port

    # - debug:
    #     msg: "add_ssh_port = {{ add_ssh_port.changed }}"

    - name: Change sel-context for port_ssh
      community.general.seport:
        ports: "{{ port_ssh }}"
        proto: tcp
        setype: ssh_port_t
        state: present
      when: add_ssh_port.changed

    - name: Deploy new ssh-config file
      ansible.builtin.copy: 
        content: |
          Port {{ port_ssh }}
          PermitRootLogin prohibit-password
          PubkeyAuthentication yes
          PasswordAuthentication yes # no
        dest: /etc/ssh/sshd_config.d/99-add-rules.conf
        owner: 'root'
        mode: '0400'
      register: add_ssh_options
      notify:
       - restart sshd

  handlers:
    - name: reload firewalld
      command: firewall-cmd --reload
      when: add_ssh_port.changed

    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: add_ssh_options.changed
...
# Run: ansible-playbook --ask-vault-pass --extra-vars '@passwd.yml' 5.Change_config_sshd.yml
# Vault password: 

# PLAY [Change port and others restrictions in config ssh] *******************************************************************************************************

# TASK [Gathering Facts] *****************************************************************************************************************************************
# ok: [rhel9v5]

# TASK [Add new ssh-port via firewalld] **************************************************************************************************************************
# changed: [rhel9v5]

# TASK [Change sel-context for port_ssh] *************************************************************************************************************************
# ok: [rhel9v5]

# TASK [Deploy new ssh-config file] ******************************************************************************************************************************
# changed: [rhel9v5]

# RUNNING HANDLER [reload firewalld] *****************************************************************************************************************************
# changed: [rhel9v5]

# RUNNING HANDLER [restart sshd] *********************************************************************************************************************************
# changed: [rhel9v5]

# PLAY RECAP *****************************************************************************************************************************************************
# rhel9v5                    : ok=7    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 