# Requered: ansible-galaxy collection install community.general
---
- name: Change password for root
  hosts: GrpRH # rhel9v5
  become: yes

  tasks:

    - name: "Set new password for root (root_pwd: from ansible-vault passwd.yml-file)"
      ansible.builtin.user:
        name: root
        password: "{{ root_pwd | password_hash('sha512', 'secretADDsalt') }}"

    - name: Set expared password now (Need change paswd in First login)
      ansible.builtin.command: /usr/bin/chage -d 0 root
      register: result

    - debug:
        msg: "Changed password for root: {{result.changed}}"
...
# Run: ansible-playbook --ask-vault-pass --extra-vars '@passwd.yml' 8.Change_pwd_root.yml 
# Vault password: 

# PLAY [Change password for root] *******************************************************************************************************************************

# TASK [Gathering Facts] *****************************************************************************************************************************************
# ok: [rhel9v5]

# TASK [Set new password for root (root_pwd: from ansible-vault passwd.yml-file)] ********************************************************************************
# changed: [rhel9v5]

# TASK [Set expared password now (Need change paswd in First login)] *********************************************************************************************
# changed: [rhel9v5]

# TASK [debug] **************************************************************************************************************************************************
# ok: [rhel9v5] => {
#     "msg": "Changed password for root: True"
# }

# PLAY RECAP *****************************************************************************************************************************************************
# rhel9v5                    : ok=4    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


   