---
all:
  vars:
    ansible_user: serp
    #ansible_sudo_pass: "{{ my_sudo_passwd }}"
    ansible_ssh_private_key_file: ~serp/.ssh/id_rsa
  children:
    GrpNew:
      hosts:
        localhost:  #Ubuntu
          ansible_host: 127.0.0.1
          port_ssh: 22          
          user_name: ansible
          user_pwd: "{{ user_pwd }}"
          root_pwd: "{{ root_pwd }}"
          ssh_pub_key: "{{ lookup('file', '~serp/.ssh/id_ed25519')  }}"      
    GrpFed:
      hosts:
        myfedora40:
          ansible_host: 169.254.27.101
          nmcli_ethernet: { ifname: enp0s3, conn_name: c_enp0s3, ip4: 169.254.27.168/16, gw4: 169.254.27.100, dns4: [192.168.54.143, 192.168.175.39, 127.0.0.1] }
    GrpRH:
      hosts:
        rhel9v5:
          ansible_host: 169.254.27.140
          ansible_port: 14582
          #port_ssh: 14582
          user_pwd: "{{ user_pwd }}"
          root_pwd: "{{ root_pwd }}"
    GrpTot:
      children:
        GrpFed:
        GrpRH:
...
